#!/bin/bash

# ============================================================================
# InfraPilot Patch Application Script
# ============================================================================
# This script applies unified diff patches generated by Cline to infrastructure
# files.
#
# Purpose:
#   - Reads patch from /tmp/cline_patch.diff
#   - Applies patch using GNU patch command
#   - Provides feedback on success or failure
#
# Usage:
#   ./scripts/apply_patch.sh [patch_file] [target_directory]
#
# Example:
#   ./scripts/apply_patch.sh
#   ./scripts/apply_patch.sh /tmp/cline_patch.diff /path/to/workspace
#
# Infinity Build Award Requirements:
#   This script demonstrates automated patch application as part of the
#   Cline integration workflow for infrastructure fix automation.
# ============================================================================

set -e  # Exit on error

# Default values
PATCH_FILE="${1:-/tmp/cline_patch.diff}"
TARGET_DIR="${2:-$(pwd)}"

echo "=========================================="
echo "InfraPilot Patch Application"
echo "=========================================="
echo "Patch file: $PATCH_FILE"
echo "Target directory: $TARGET_DIR"
echo ""

# Check if patch file exists
if [ ! -f "$PATCH_FILE" ]; then
    echo "Error: Patch file not found: $PATCH_FILE"
    echo ""
    echo "Please ensure a patch has been generated first:"
    echo "  ./scripts/run_cline.sh <file_path> <issue_description>"
    exit 1
fi

# Check if patch file is not empty
if [ ! -s "$PATCH_FILE" ]; then
    echo "Error: Patch file is empty: $PATCH_FILE"
    exit 1
fi

# Check if target directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: Target directory not found: $TARGET_DIR"
    exit 1
fi

# Check if GNU patch command is available
if ! command -v patch &> /dev/null; then
    echo "Error: GNU 'patch' command not found in PATH"
    echo ""
    echo "Please install patch utility:"
    echo "  - macOS: Already installed or via Homebrew"
    echo "  - Linux: sudo apt-get install patch (Debian/Ubuntu)"
    echo "           sudo yum install patch (RHEL/CentOS)"
    echo "  - Windows: Install via Git for Windows or WSL"
    exit 1
fi

echo "[Patch] Applying patch to workspace..."
echo ""

# Apply patch using GNU patch command
# Options:
#   -p1: Strip one leading slash from paths
#   -i: Input patch file
#   --dry-run: First do a dry run to check for errors
#   --backup: Create backup files

# First, do a dry run to check for issues
echo "[Patch] Performing dry run..."
if patch -p1 --dry-run -i "$PATCH_FILE" -d "$TARGET_DIR" > /dev/null 2>&1; then
    echo "[Patch] Dry run successful. Applying patch..."
    
    # Apply the patch for real
    if patch -p1 -i "$PATCH_FILE" -d "$TARGET_DIR" --backup; then
        echo ""
        echo "=========================================="
        echo "Patch Applied Successfully"
        echo "=========================================="
        echo "The patch has been applied to files in: $TARGET_DIR"
        echo ""
        echo "Backup files have been created with .orig extension"
        echo "Review the changes and commit if satisfied."
        exit 0
    else
        echo ""
        echo "=========================================="
        echo "Patch Application Failed"
        echo "=========================================="
        echo "The patch could not be applied. Possible reasons:"
        echo "  1. File paths in patch don't match workspace structure"
        echo "  2. Target files have been modified since patch was generated"
        echo "  3. Patch format is invalid"
        echo ""
        echo "Try applying manually or regenerate the patch."
        exit 1
    fi
else
    echo ""
    echo "=========================================="
    echo "Patch Dry Run Failed"
    echo "=========================================="
    echo "The patch cannot be applied. Checking details..."
    echo ""
    
    # Show detailed error
    patch -p1 --dry-run -i "$PATCH_FILE" -d "$TARGET_DIR" 2>&1 || true
    
    echo ""
    echo "Please review the errors above and fix the issues before applying."
    exit 1
fi

